export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";
export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const POST_CATEGORY_FAIL = "POST_CATEGORY_FAIL";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL"
export const DELET_CATEGORY_SUCCESS = "DELET_CATEGORY_SUCCESS";
export const DELET_CATEGORY_FAIL = "DELET_CATEGORY_FAIL";
export const GET_CATEGORY_ID_SUCCESS = "GET_CATEGORY_ID_SUCCESS";
export const GET_CATEGORY_ID_FAIL = "GET_CATEGORY_ID_FAIL"

export const GET_SATUAN_SUCCESS = "GET_SATUAN_SUCCESS";
export const GET_SATUAN_FAIL = "GET_SATUAN_FAIL";
export const POST_SATUAN_SUCCESS = "POST_SATUAN_SUCCESS";
export const POST_SATUAN_FAIL = "POST_SATUAN_FAIL";
export const EDIT_SATUAN_SUCCESS = "EDIT_SATUAN_SUCCES";
export const EDIT_SATUAN_FAIL = "EDIT_SATUAN_FAIL";
export const DELET_SATUAN_SUCCES = "DELET_SATUAN_SUCCESS";
export const DELET_SATUAN_FAIL = "DELET_SATUAN_SUCCESS";
export const GET_SATUAN_ID_SUCCESS = "GET_SATUAN_ID_SUCCESS";
export const GET_SATUAN_ID_FAIL = "GET_SATUAN_ID_FAIL";

export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAIL = "GET_ITEM_FAIL";
export const POST_ITEM_SUCCESS = "POST_ITEM_SUCCESS";
export const POST_ITEM_FAIL = "POST_ITEM_FAIL";
export const EDIT_ITEM_SUCCESS = "EDIT_ITEM_SUCCESS";
export const EDIT_ITEM_FAIL = "EDIT_ITEM_FAIL";
export const DELET_ITEM_SUCCESS = "DELET_ITEM_SUCCESS";
export const DELET_ITEM_FAIL = "DELET_ITEM_FIAL";
export const GET_ITEM_ID_SUCCESS = "GET_ITEM_ID_SUCCESS";
export const GET_ITEM_ID_FAIL = "GET_ITEM_ID_FAIL";

export const GET_SALES_SUCCESS = "GET_SALES_SUCCESS";
export const GET_SALES_FAIL = "GET_SALES_FAIL";
export const POST_SALES_SUCCESS = "POST_SALES_SUCCESS";
export const POST_SALES_FAIL = "POST_SALES_FAIL";
export const EDIT_SALES_SUCCESS = "EDIT_SALES_SUCCESS";
export const EDIT_SALES_FAIL = "EDIT_SALES_FAIL";
export const DELET_SALES_SUCCESS = "DELET_SALES_SUCCESS";
export const DELET_SALES_FAIL =  "DELET_SALES_FAIL";
export const GET_SALES_ID_SUCCESS ="GET_SELES_ID_SUCCESS";
export const GET_SALES_ID_FAIL = "GET_SALES_ID_FAIL";

export const GET_TRANSAKSI_INPUT_SUCCESS = "GET_TRANSAKSI_INPUT_SUCCESS";
export const GET_TRANSAKSI_INPUT_FAIL = "GET_TRANSAKSI_INPUT_FAIL";
export const POST_TRANSAKSI_INPUT_SUCCESS = "POST_TRANSAKSI_INPUT_SUCCESS";
export const POST_TRANSAKSI_INPUT_FAIL = "POST_TRANSAKSI_INPUT_SUCCESS";
export const EDIT_TRANSAKSI_INPUT_SUCCESS = "EDIT_TRANSAKSI_INPUT_SUCCESS";
export const EDIT_TRANSAKSI_INPUT_FAIL = "EDIT_TRANSAKSI_INPUT_FAIL";
export const DELET_TRANSAKSI_INPUT_SUCCESS = "DELET_TRANSAKSI_INPUT_SUCCESS";
export const DELET_TRANSAKSI_INPUT_FAIL = "DELET_TRANSAKSI_INPUT_FAIL";

export const GET_BUYITEM_SUCCESS = "GET_BUTITEM_SUCCESS";
export const GET_BUYITEM_FAIL = "GET_BUYITEM_FAIL";
export const POST_BUYITEM_SUCCESS = "POST_BUYITEM_SUCCESS";
export const POST_BUYITEM_FAIL = "POST_BUYITEM_FAIL";
export const EDIT_BUYITEM_SUCCESS = "EDIT_BUYITEM_SUCCESS";
export const EDIT_BUYITEM_FAIL = "EDIT_BUYITEM_FAIL";
export const DELET_BUYITEM_SUCCESS = "DELET_BUYITEM_SUCCESS";
export const DELET_BUYITEM_FAIL = "DELET_BUYITEM_FAIL";

export const POST_TMASUK_SUCCESS = "POST_TMASUK_SUCCESS";
export const POST_TMASUK_FAIL = "POST_TMASUK_FAIL";
export const GET_TMASUK_SUCCESS = "GET_TMASUK_SUCCESS";
export const GET_TMASUK_FAIL = "GET_TMASUK_FAIL";
export const EDIT_TMASUK_SUCCESS = "EDIT_TMASUK_SUCCESS";
export const EDIT_TMASUK_FAIL = "EDIT_TMASUK_FAIL";
export const DELET_TMASUK_SUCCESS = "DELET_TMASUK_SUCCESS";
export const DELET_TMASUK_FAIL = "DELET_TMASUK_FAIL";
export const GET_TMASUK_ID_SUCCESS = "GET_TMASUK_ID_SUCCESS";
export const GET_TMASUK_ID_FAIL = "GET_TMASUK_ID_FAIL";

export const POST_BUYER_SUCCESS = "POST_BUYER_SUCCESS";
export const POST_BUYER_FAIL = "POST_BUYER_FAIL";
export const EDIT_BUYER_SUCCESS =  "EDIT_BUYER_SUCCESS"
export const EDIT_BUYER_FAIL = "EDIT_BUYER_FAIL";
export const DELET_BUYER_SUCCES = "DELET_BUYER_SUCCESS";
export const DELET_BUYER_FAIL = "DELET_BUYER_FAIL";
export const GET_BUYER_SUCCESS = "GET_BUYER_SUCCES";
export const GET_BUYER_FAIL = "GET_BUYER_FAIL";
export const GET_BUYER_ID_SUCCESS = "GET_BUYER_ID_SUCCESS";
export const GET_BUYER_ID_FAIL = "GET_BUYER_ID_FAIL";

export const POST_TKELUAR_SUCCESS = "POST_TKELUAR_SUCCESS";
export const POST_TKELUAR_FAIL = "POST_TKELUAR_FAIL";
export const GET_TKELUAR_SUCCESS = "GET_TKELUAR_SUCCESS";
export const GET_TKELUAR_FAIL = "GET_TKELUAR_FAIL";
export const EDIT_TKELUAR_SUCCESS = "EDIT_TKELUAR_SUCCESS";
export const EDIT_TKELUAR_FAIL = "EDIT_TKELUAR_FAIL";
export const DELET_TKELUAR_SUCCESS = "DELET_TKELUAR_SUCCESS";
export const DELET_TKELUAR_FAIL = "DELET_TKELUAR_FAIL";
export const GET_TKELUAR_ID_SUCCESS = "GET_TKELUAR_ID_SUCCESS";
export const GET_TKELUAR_ID_FAIL = "GET_TKELUAR_ID_FAIL";

export const GET_SALEITEM_SUCCESS = "GET_SALEITEM_SUCCESS";
export const GET_SALEITEM_FAIL = "GET_SALEITEM_FAIL";
export const POST_SALEITEM_SUCCESS = "POST_SALEITEM_SUCCESS";
export const POST_SALEITEM_FAIL = "POST_SALEITEM_FAIL";
export const EDIT_SALEITEM_SUCCESS = "EDIT_SALEITEM_SUCCESS";
export const EDIT_SALEITEM_FAIL = "EDIT_SALEITEM_FAIL";
export const DELET_SALEITEM_SUCCESS = "DELET_SALEITEM_SUCCESS";
export const DELET_SALEITEM_FAIL = "DELET_SALEITEM_FAIL";